{
  "url": "https://api.github.com/repos/MystPi/ninetails/releases/55549676",
  "assets_url": "https://api.github.com/repos/MystPi/ninetails/releases/55549676/assets",
  "upload_url": "https://uploads.github.com/repos/MystPi/ninetails/releases/55549676/assets{?name,label}",
  "html_url": "https://github.com/MystPi/ninetails/releases/tag/v2.2.3",
  "id": 55549676,
  "author": {
    "login": "MystPi",
    "id": 86574651,
    "node_id": "MDQ6VXNlcjg2NTc0NjUx",
    "avatar_url": "https://avatars.githubusercontent.com/u/86574651?v=4",
    "gravatar_id": "",
    "url": "https://api.github.com/users/MystPi",
    "html_url": "https://github.com/MystPi",
    "followers_url": "https://api.github.com/users/MystPi/followers",
    "following_url": "https://api.github.com/users/MystPi/following{/other_user}",
    "gists_url": "https://api.github.com/users/MystPi/gists{/gist_id}",
    "starred_url": "https://api.github.com/users/MystPi/starred{/owner}{/repo}",
    "subscriptions_url": "https://api.github.com/users/MystPi/subscriptions",
    "organizations_url": "https://api.github.com/users/MystPi/orgs",
    "repos_url": "https://api.github.com/users/MystPi/repos",
    "events_url": "https://api.github.com/users/MystPi/events{/privacy}",
    "received_events_url": "https://api.github.com/users/MystPi/received_events",
    "type": "User",
    "site_admin": false
  },
  "node_id": "RE_kwDOGZq_084DT57s",
  "tag_name": "v2.2.3",
  "target_commitish": "main",
  "name": "Version 2.2.3",
  "draft": false,
  "prerelease": false,
  "created_at": "2021-12-17T14:43:30Z",
  "published_at": "2021-12-17T14:45:02Z",
  "assets": [
    {
      "url": "https://api.github.com/repos/MystPi/ninetails/releases/assets/52018831",
      "id": 52018831,
      "node_id": "RA_kwDOGZq_084DGb6P",
      "name": "ninetails-2.2.3-1.x86_64.rpm",
      "label": "",
      "uploader": {
        "login": "github-actions[bot]",
        "id": 41898282,
        "node_id": "MDM6Qm90NDE4OTgyODI=",
        "avatar_url": "https://avatars.githubusercontent.com/in/15368?v=4",
        "gravatar_id": "",
        "url": "https://api.github.com/users/github-actions%5Bbot%5D",
        "html_url": "https://github.com/apps/github-actions",
        "followers_url": "https://api.github.com/users/github-actions%5Bbot%5D/followers",
        "following_url": "https://api.github.com/users/github-actions%5Bbot%5D/following{/other_user}",
        "gists_url": "https://api.github.com/users/github-actions%5Bbot%5D/gists{/gist_id}",
        "starred_url": "https://api.github.com/users/github-actions%5Bbot%5D/starred{/owner}{/repo}",
        "subscriptions_url": "https://api.github.com/users/github-actions%5Bbot%5D/subscriptions",
        "organizations_url": "https://api.github.com/users/github-actions%5Bbot%5D/orgs",
        "repos_url": "https://api.github.com/users/github-actions%5Bbot%5D/repos",
        "events_url": "https://api.github.com/users/github-actions%5Bbot%5D/events{/privacy}",
        "received_events_url": "https://api.github.com/users/github-actions%5Bbot%5D/received_events",
        "type": "Bot",
        "site_admin": false
      },
      "content_type": "binary/octet-stream",
      "state": "uploaded",
      "size": 79155200,
      "download_count": 1,
      "created_at": "2021-12-17T14:48:07Z",
      "updated_at": "2021-12-17T14:48:11Z",
      "browser_download_url": "https://github.com/MystPi/ninetails/releases/download/v2.2.3/ninetails-2.2.3-1.x86_64.rpm"
    },
    {
      "url": "https://api.github.com/repos/MystPi/ninetails/releases/assets/52018903",
      "id": 52018903,
      "node_id": "RA_kwDOGZq_084DGb7X",
      "name": "Ninetails-2.2.3.Setup.exe",
      "label": "",
      "uploader": {
        "login": "github-actions[bot]",
        "id": 41898282,
        "node_id": "MDM6Qm90NDE4OTgyODI=",
        "avatar_url": "https://avatars.githubusercontent.com/in/15368?v=4",
        "gravatar_id": "",
        "url": "https://api.github.com/users/github-actions%5Bbot%5D",
        "html_url": "https://github.com/apps/github-actions",
        "followers_url": "https://api.github.com/users/github-actions%5Bbot%5D/followers",
        "following_url": "https://api.github.com/users/github-actions%5Bbot%5D/following{/other_user}",
        "gists_url": "https://api.github.com/users/github-actions%5Bbot%5D/gists{/gist_id}",
        "starred_url": "https://api.github.com/users/github-actions%5Bbot%5D/starred{/owner}{/repo}",
        "subscriptions_url": "https://api.github.com/users/github-actions%5Bbot%5D/subscriptions",
        "organizations_url": "https://api.github.com/users/github-actions%5Bbot%5D/orgs",
        "repos_url": "https://api.github.com/users/github-actions%5Bbot%5D/repos",
        "events_url": "https://api.github.com/users/github-actions%5Bbot%5D/events{/privacy}",
        "received_events_url": "https://api.github.com/users/github-actions%5Bbot%5D/received_events",
        "type": "Bot",
        "site_admin": false
      },
      "content_type": "binary/octet-stream",
      "state": "uploaded",
      "size": 85504512,
      "download_count": 6,
      "created_at": "2021-12-17T14:49:10Z",
      "updated_at": "2021-12-17T14:49:14Z",
      "browser_download_url": "https://github.com/MystPi/ninetails/releases/download/v2.2.3/Ninetails-2.2.3.Setup.exe"
    },
    {
      "url": "https://api.github.com/repos/MystPi/ninetails/releases/assets/52018991",
      "id": 52018991,
      "node_id": "RA_kwDOGZq_084DGb8v",
      "name": "Ninetails-darwin-x64-2.2.3.zip",
      "label": "",
      "uploader": {
        "login": "github-actions[bot]",
        "id": 41898282,
        "node_id": "MDM6Qm90NDE4OTgyODI=",
        "avatar_url": "https://avatars.githubusercontent.com/in/15368?v=4",
        "gravatar_id": "",
        "url": "https://api.github.com/users/github-actions%5Bbot%5D",
        "html_url": "https://github.com/apps/github-actions",
        "followers_url": "https://api.github.com/users/github-actions%5Bbot%5D/followers",
        "following_url": "https://api.github.com/users/github-actions%5Bbot%5D/following{/other_user}",
        "gists_url": "https://api.github.com/users/github-actions%5Bbot%5D/gists{/gist_id}",
        "starred_url": "https://api.github.com/users/github-actions%5Bbot%5D/starred{/owner}{/repo}",
        "subscriptions_url": "https://api.github.com/users/github-actions%5Bbot%5D/subscriptions",
        "organizations_url": "https://api.github.com/users/github-actions%5Bbot%5D/orgs",
        "repos_url": "https://api.github.com/users/github-actions%5Bbot%5D/repos",
        "events_url": "https://api.github.com/users/github-actions%5Bbot%5D/events{/privacy}",
        "received_events_url": "https://api.github.com/users/github-actions%5Bbot%5D/received_events",
        "type": "Bot",
        "site_admin": false
      },
      "content_type": "binary/octet-stream",
      "state": "uploaded",
      "size": 82778310,
      "download_count": 0,
      "created_at": "2021-12-17T14:50:37Z",
      "updated_at": "2021-12-17T14:50:41Z",
      "browser_download_url": "https://github.com/MystPi/ninetails/releases/download/v2.2.3/Ninetails-darwin-x64-2.2.3.zip"
    },
    {
      "url": "https://api.github.com/repos/MystPi/ninetails/releases/assets/52018825",
      "id": 52018825,
      "node_id": "RA_kwDOGZq_084DGb6J",
      "name": "ninetails_2.2.3_amd64.deb",
      "label": "",
      "uploader": {
        "login": "github-actions[bot]",
        "id": 41898282,
        "node_id": "MDM6Qm90NDE4OTgyODI=",
        "avatar_url": "https://avatars.githubusercontent.com/in/15368?v=4",
        "gravatar_id": "",
        "url": "https://api.github.com/users/github-actions%5Bbot%5D",
        "html_url": "https://github.com/apps/github-actions",
        "followers_url": "https://api.github.com/users/github-actions%5Bbot%5D/followers",
        "following_url": "https://api.github.com/users/github-actions%5Bbot%5D/following{/other_user}",
        "gists_url": "https://api.github.com/users/github-actions%5Bbot%5D/gists{/gist_id}",
        "starred_url": "https://api.github.com/users/github-actions%5Bbot%5D/starred{/owner}{/repo}",
        "subscriptions_url": "https://api.github.com/users/github-actions%5Bbot%5D/subscriptions",
        "organizations_url": "https://api.github.com/users/github-actions%5Bbot%5D/orgs",
        "repos_url": "https://api.github.com/users/github-actions%5Bbot%5D/repos",
        "events_url": "https://api.github.com/users/github-actions%5Bbot%5D/events{/privacy}",
        "received_events_url": "https://api.github.com/users/github-actions%5Bbot%5D/received_events",
        "type": "Bot",
        "site_admin": false
      },
      "content_type": "binary/octet-stream",
      "state": "uploaded",
      "size": 71608228,
      "download_count": 0,
      "created_at": "2021-12-17T14:48:03Z",
      "updated_at": "2021-12-17T14:48:06Z",
      "browser_download_url": "https://github.com/MystPi/ninetails/releases/download/v2.2.3/ninetails_2.2.3_amd64.deb"
    }
  ],
  "tarball_url": "https://api.github.com/repos/MystPi/ninetails/tarball/v2.2.3",
  "zipball_url": "https://api.github.com/repos/MystPi/ninetails/zipball/v2.2.3",
  "body": "This release greatly improves tabs by giving them a min-width and letting them scroll horizontally if they have to. This means that you can have as many tabs as you want without them getting too squished.\r\n\r\nThis release also adds a link to this repository in the 'more' menu, and fixes a few bugs.",
  "reactions": {
    "url": "https://api.github.com/repos/MystPi/ninetails/releases/55549676/reactions",
    "total_count": 1,
    "+1": 1,
    "-1": 0,
    "laugh": 0,
    "hooray": 0,
    "confused": 0,
    "heart": 0,
    "rocket": 0,
    "eyes": 0
  }
}
